// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlxskifcnhlseeednugo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseHNraWZjbmhsc2VlZWRudWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MjYzNzQsImV4cCI6MjA3ODIwMjM3NH0.uXTdN_tSw_5E9MRk9VM3n83ap2XzX55BGv29Ph_cQuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});